[package]
name = "wasmer/bash"
version = "1.0.25"
description = "Bash is a modern POSIX-compliant implementation of /bin/sh."
license = "GNU"
wasmer-extra-flags = "--enable-threads --enable-bulk-memory"
entrypoint = "bash"

[dependencies]
"wasmer/coreutils" = "1.0.19"

[[module]]
name = "bash"
source = "bash.wasm"
abi = "wasi"

[[command]]
name = "bash"
module = "bash"
runner = "wasi@unstable_"

[[command]]
name = "sh"
module = "bash"
runner = "wasi@unstable_"
